<a href="https://colab.research.google.com/github/Gayathri7841/AI-Learning-Journey/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.2


In [4]:
list=[1,2,3,4]

print(list*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [5]:
arr=np.array([1,2,3,4])
print(arr*2)

[2 4 6 8]


In [6]:
arr=np.array(1)
print(arr.ndim)

0


In [7]:
arr=np.array([1,2,3])
print(arr.ndim)

1


In [11]:
arr=np.array([[1 ,2, 3],[1 ,3 ,2]])
print(arr.ndim)


2


In [12]:
arr=np.array([[[1,8,6],[7,9,6],[7,5,4]]])
print(arr.ndim)

3


In [16]:
arr=np.array([
    [
    [[7,8,44],[88,55,77],[5,7,8],[88,77,66]],
    [[88,54,63],[78,56,77],[88,8,8],[5,5,5]],
               ]])
print(arr.ndim)
print(arr.shape)

4
(1, 2, 4, 3)


# **Arrays Slicing**
# array[start:end:step]

In [29]:
arr=np.array([
              [1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]
              ])
print(arr.ndim)
print(arr.shape)

2
(4, 4)


In [30]:

print(arr[0])

[1 2 3 4]


In [42]:
print(arr[0][3])

4


In [44]:
print(arr[0, 3])

4


In [48]:
print(arr[0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [49]:
print(arr[ :,0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [50]:
print(arr[2:3,1:2])

[[10]]


In [51]:
print(arr[2:3,1:2][0,0])


10


In [31]:
print(arr[-1])

[13 14 15 16]


In [32]:
print(arr[0:4:1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [33]:
print(arr[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [34]:
print(arr[:,2])#to print 2nd col elements from all rows

[ 3  7 11 15]


In [35]:
print(arr[:,0:3])# to print all cols in range  0 to 3 from all rows

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [40]:
print(arr[1:2,1:2])

[[6]]


In [41]:
print(arr[1:2,1:2][0,0])

6


# **Arithmetic Operations on Arrays**

In [52]:
arr=np.array([1,3,4,5,6,7,8,9])


In [53]:
print(arr+1)

[ 2  4  5  6  7  8  9 10]


In [54]:
print(arr-2)

[-1  1  2  3  4  5  6  7]


In [55]:
print(arr*2)

[ 2  6  8 10 12 14 16 18]


In [56]:
print(arr/2)

[0.5 1.5 2.  2.5 3.  3.5 4.  4.5]


In [57]:
print(arr**2)

[ 1  9 16 25 36 49 64 81]


# **Vectorized Math functions**

In [58]:
print(np.sqrt(arr))

[1.         1.73205081 2.         2.23606798 2.44948974 2.64575131
 2.82842712 3.        ]


In [59]:
arr=np.array([1.26,2.99,3.45,6.5])
print(np.round(arr))

[1. 3. 3. 6.]


In [60]:
print(np.floor(arr))

[1. 2. 3. 6.]


In [61]:
print(np.pi)

3.141592653589793


In [62]:
r=np.array([1,2,3])
print(np.pi*r**2)

[ 3.14159265 12.56637061 28.27433388]


In [67]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1**a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


# **Comparison Operators on Arrays**

In [68]:
arr=np.array([100,200,100,400,100])
print(arr==100)

[ True False  True False  True]


In [69]:
print(arr>100)

[False  True False  True False]


In [70]:
print(arr<100)

[False False False False False]


In [71]:
print(arr!=100)

[False  True False  True False]


In [72]:
print(arr>=100)

[ True  True  True  True  True]


In [73]:
print(arr<=100)

[ True False  True False  True]


# **Broadcasting**
both arrays should be either of same size or one among them should have size=1

In [75]:
a1=np.array([[1,2,3,4]])
a2=np.array([[1],[2],[3],[4]])
print(a1.shape)
print(a2.shape)

(1, 4)
(4, 1)


In [76]:
print(a1*a2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


# **Aggregate Functions**

In [77]:
array=np.array([[1,2,3,4],[5,6,7,8]])
print(np.sum(array))

36


In [85]:
print(np.sum(array,axis=0))

[ 6  8 10 12]


In [86]:
print(np.sum(array , axis=1))

[10 26]


In [78]:
print(np.mean(array))

4.5


In [79]:
print(np.std(array))

2.29128784747792


In [80]:
print(np.var(array))

5.25


In [81]:
print(np.min(array))

1


In [82]:
print(np.max(array))

8


In [83]:
print(np.argmin(array))

0


In [84]:
print(np.argmax(array))

7


# **Filtering**

In [92]:
ages=np.array([[21,17,41,16,22,44,77,55],[39,25,55,53,46,31,18,19]])
teenagers=ages[ages<18]
adults=ages[ages>=18]
adults1=ages[(ages>=18)&(ages<=65)]
print(adults1)
print(adults)
print(teenagers)

[21 41 22 44 55 39 25 55 53 46 31 18 19]
[21 41 22 44 77 55 39 25 55 53 46 31 18 19]
[17 16]


# **Random Numbers**

In [93]:
rng=np.random.default_rng()

In [97]:
print(rng.integers(1,7))

3


In [101]:
print(rng.integers(low=1,high=107,size=4))

[11 94 42 20]


In [102]:
print(rng.integers(low=1,high=107,size=(3,2)))

[[24 37]
 [11 11]
 [72 10]]


In [110]:
print(np.random.uniform())
np.random.seed(seed=1)# u will get same values if u use the same seed
print(np.random.uniform(low=-1,high=2,size=5))

0.0923385947687978
[ 0.25106601  1.16097348 -0.99965688 -0.09300228 -0.55973233]


In [113]:
rng=np.random.default_rng()
array=np.array([1,2,3,4])
rng.shuffle(array)
print(array)

[1 2 3 4]
